### ISSUE TITLE
Créer ApiService

### ISSUE THREAD

**Issue by Franfran62** [Franfran62/la-bonne-franquette-appli#1]
## Description :

Concevoir et implémenter l'ApiService pour gérer les appels d'API. Ce service doit prendre en compte le token fourni par le TokenProvider

## Tâches :

- Créer la classe ApiService dans le répertoire /lib/service.
- Concevoir l'architecture de la classe selon le schéma global fourni ci dessous.
- Utiliser SecuredStorage pour récupérer l'URL de l'API lors de l'initialisation de l'ApiService.
- Utiliser le TokenProvider pour gérer le token d'authentification.
- Implémenter des méthodes privées pour définir et obtenir le token d'authentification.
- Implémenter des méthodes publiques pour les appels d'API : get, post, put, delete, patch.
#### Notes : 
Les méthodes get, post, put, delete, patch doivent prendre en charge la gestion du token d'authentification fourni par le TokenProvider via un boolean token passé en paramètre de fonction. Selon ce boolean, le token se nommant "auth-token" doit-être fourni en header de requête. Si la requête échoue, ces fonctions doivent lever une Exception

## Critères d'acceptation :

- L'ApiService est conçu et implémenté selon le schéma global fourni.
- L'URL de l'API est récupérée en toute sécurité à partir de SecuredStorage.
- Le token d'authentification est géré de manière sécurisée à l'aide du TokenProvider.
- Les méthodes d'appel d'API prennent en charge la gestion du token d'authentification fourni par le TokenProvider.
- Les méthodes d'appel d'Api remonte une exception si une erreur se présente

## Schema global de l'entité 

+ private string ApiUrl 

__construct() : 
get ApiUrl from SecuredStorage; 

- private function getToken() : String // utilise le TokenProvider
- public function get(String endpoint, bool token=false) : Json throw Exception
- public function post(String endpoint, bool token=false) : Json throw Exception
- public function put(String endpoint, bool token=false) : Json throw Exception
- public function delete(String endpoint, bool token=false) : Json throw Exception
- public function patch(String endpoint, bool token=false) : Json  throw Exception
-

**Comment by iDrack** [comment]
Je pense pas qu'il y ai besoin de créer une classe a proprement parler.

**Comment by iDrack** [comment]
Je peux ajouter med queryBuilders à la classe où on fait ça a part ?

**Comment by iDrack** [comment]
On peut directement décoder le json pour avoir une Map<String, dynamic>, ce serait mieux non ? En plus ça respecterai le principe DRY
