### ISSUE TITLE
Refacto : ApiService divise par 3

### ISSUE THREAD

**Issue by Franfran62** [Franfran62/la-bonne-franquette-appli#42]
## Description

ApiService fait bien trop de trucs, enlever les routes qui ne servent pas encore, et scinder la partie connection dans le connection_service, et rajouter un service pour y voir plus clair avec les besoins

## Details

TestConnection(), setBaseAdressServeur(), login(), logout() ===> ConnectionService
Get(), Post(), FetchAll(), Put(), Delete() =====> ApiService
GetToken(), GetCacheVersion(), setBaseAdresse(), setHeaders() ===> ApiUtilsService

Mettre ces 3 fichiers dans un dossier Service/Api

**Comment by iDrack** [comment]
Changer le setHeader() de class est une mauvaise idée, setHeader est un setter de la class ApiService et setBaseAdresse() n'éxiste pas
